# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Makdempu Movie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Makdempu Movie
  pod 'UIScrollView-InfiniteScroll', '~> 1.3.0'
  pod 'youtube-ios-player-helper'

end
