//
//  GenrePresenter.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 12/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class GenrePresenter {
    
    // MARK: - Private properties -

    private unowned let view: GenreViewInterface
    private let interactor: GenreInteractorInterface
    private let wireframe: GenreWireframeInterface

    // MARK: - Lifecycle -

    init(view: GenreViewInterface, interactor: GenreInteractorInterface, wireframe: GenreWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension GenrePresenter: GenrePresenterInterface {
    func interactorDidFetchGenre(with result: Result<[Genre], Error>) {
        switch result {
        case .success(let genres):
            view.update(with: genres)
        case .failure:
            view.update(with: "Periksa kembali internet anda")
        }
    }
    
    func fetchListGenre() {
        interactor.fetchListGenre()
    }
}
