//
//  GenreInteractor.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 12/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class GenreInteractor {
}

// MARK: - Extensions -

extension GenreInteractor: GenreInteractorInterface {
}
