//
//  GenreInterfaces.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 12/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol GenreWireframeInterface: WireframeInterface {
}

protocol GenreViewInterface: ViewInterface {
}

protocol GenrePresenterInterface: PresenterInterface {
}

protocol GenreInteractorInterface: InteractorInterface {
}
