//
//  ReviewPresenter.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 13/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ReviewPresenter {
    
    // MARK: - Private properties -

    private unowned let view: ReviewViewInterface
    private let interactor: ReviewInteractorInterface
    private let wireframe: ReviewWireframeInterface

    // MARK: - Lifecycle -

    init(view: ReviewViewInterface, interactor: ReviewInteractorInterface, wireframe: ReviewWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ReviewPresenter: ReviewPresenterInterface {
    func navigateBack() {
        wireframe.navigateBack()
    }
    
    func getAdditionalReviews(with movieId: Int, completion: @escaping ([Review]) -> Void) {
        interactor.fetchAdditionalReviews(with: movieId) { result in
            switch result {
            case .success(let reviews):
                completion(reviews)
            case .failure:
                completion([])
            }
        }
    }
    
    func getReviewList(with movieId: Int) {
        interactor.fetchReviewList(with: movieId)
    }
    
    func interactorDidFetchReviews(with result: Result<[Review], Error>) {
        switch result {
        case .success(let reviews):
            view.update(with: reviews)
        case .failure:
            view.update(with: "Periksa kembali koneksi internet anda")
        }
    }
    
}
