//
//  ReviewWireframe.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 13/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ReviewWireframe: BaseWireframe<ReviewViewController> {

    // MARK: - Module setup -

    init(movieId: Int) {
        let moduleViewController = ReviewViewController()
        super.init(viewController: moduleViewController)
        moduleViewController.movieId = movieId

        let interactor = ReviewInteractor()
        let presenter = ReviewPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }

}

// MARK: - Extensions -

extension ReviewWireframe: ReviewWireframeInterface {
    func navigateBack() {
        navigationController?.popViewController(animated: true)
    }
    
}
