//
//  ReviewInterfaces.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 13/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ReviewWireframeInterface: WireframeInterface {
}

protocol ReviewViewInterface: ViewInterface {
    func update(with reviews: [Review])
    
    func update(with error: String)
}

protocol ReviewPresenterInterface: PresenterInterface {
    func getReviewList(with movieId: Int)
    
    func getAdditionalReviews(with movieId: Int, completion: @escaping ([Review]) -> Void)
    
    func interactorDidFetchReviews(with result: Result<[Review], Error>)
}

protocol ReviewInteractorInterface: InteractorInterface {
    func fetchReviewList(with movieId: Int)
    
    func fetchAdditionalReviews(with movieId: Int, completion: @escaping (Result<[Review], Error>) -> Void)
}
