//
//  MovieListWireframe.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 13/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieListWireframe: BaseWireframe<MovieListViewController> {

    // MARK: - Module setup -

    init(genreId: Int) {
        let moduleViewController = MovieListViewController()
        super.init(viewController: moduleViewController)
        moduleViewController.genreId = genreId

        let interactor = MovieListInteractor()
        let presenter = MovieListPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }

}

// MARK: - Extensions -

extension MovieListWireframe: MovieListWireframeInterface {
}
