//
//  MovieListInterfaces.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 13/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieListWireframeInterface: WireframeInterface {
    func routeToDetail(with movieId: Int)
    
    func navigateBack()
}

protocol MovieListViewInterface: ViewInterface {
    func update(with movies: [Movie])
    
    func update(with error: String)
}

protocol MovieListPresenterInterface: PresenterInterface {
    func getMovieList(with genreId: Int)
    
    func interactorDidFetchMovies(with result: Result<[Movie], Error>)
    
    func getAdditionalMovies(with genreId: Int, completion: @escaping ([Movie]) -> Void)
    
    func goToDetail(with movieId: Int)
    
    func navigateBack()
}

protocol MovieListInteractorInterface: InteractorInterface {
    func fetchMovieList(with genreId: Int)
    
    func fetchAdditionalMovies(with genreId: Int, completion: @escaping (Result<[Movie], Error>) -> Void)
}
