//
//  MovieListInteractor.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 13/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieListInteractor {
    var presenter: MovieListPresenter?
}

// MARK: - Extensions -

extension MovieListInteractor: MovieListInteractorInterface {
    func fetchMovieList(with genreId: Int) {
        guard let url = URL(string: "\(APIConstants.baseURL)/discover/movie\(APIConstants.key)&with_genres=\(genreId)") else { return }
        let task = URLSession.shared.dataTask(with: url) { [weak self] data, response, error in
            guard let data = data, error == nil else {
                return
            }
//            let outputStr  = String(data: data, encoding: String.Encoding.utf8)! as String
            do {
                let entities = try JSONDecoder().decode(MovieResponse.self, from: data)
                self?.presenter?.interactorDidFetchMovie(with: .success(entities.results))
            }
            catch {
                self?.presenter?.interactorDidFetchMovie(with: .failure(error))
            }
        }
        task.resume()
    }
    
}
