//
//  MovieListInteractor.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 13/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieListInteractor {
    var presenter: MovieListPresenter?
    var page = 1
}

// MARK: - Extensions -

extension MovieListInteractor: MovieListInteractorInterface {
    func fetchMovieList(with genreId: Int) {
        guard let url = URL(string: "\(APIConstants.baseURL)/discover/movie\(APIConstants.key)&with_genres=\(genreId)&page=\(page)") else { return }
        let task = URLSession.shared.dataTask(with: url) { [weak self] data, response, error in
            guard let data = data, error == nil else {
                self?.presenter?.interactorDidFetchMovies(with: .failure(error!))
                return
            }
            do {
                let entities = try JSONDecoder().decode(MovieResponse.self, from: data)
                self?.presenter?.interactorDidFetchMovies(with: .success(entities.results))
                self?.page += 1
            }
            catch {
                self?.presenter?.interactorDidFetchMovies(with: .failure(error))
            }
        }
        task.resume()
    }
    
    func fetchAdditionalMovies(with genreId: Int, completion: @escaping (Result<[Movie], Error>) -> Void) {
        guard let url = URL(string: "\(APIConstants.baseURL)/discover/movie\(APIConstants.key)&with_genres=\(genreId)&page=\(page)") else { return }
        let task = URLSession.shared.dataTask(with: url) { [weak self] data, response, error in
            guard let data = data, error == nil else {
                self?.presenter?.interactorDidFetchMovies(with: .failure(error!))
                return
            }
            do {
                let entities = try JSONDecoder().decode(MovieResponse.self, from: data)
                completion(.success(entities.results))
                self?.page += 1
            }
            catch {
                completion(.failure(error))
            }
        }
        task.resume()
    }
}
