//
//  MovieDetailPresenter.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 13/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieDetailPresenter {
    
    // MARK: - Private properties -

    private unowned let view: MovieDetailViewInterface
    private let interactor: MovieDetailInteractorInterface
    private let wireframe: MovieDetailWireframeInterface

    // MARK: - Lifecycle -

    init(view: MovieDetailViewInterface, interactor: MovieDetailInteractorInterface, wireframe: MovieDetailWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MovieDetailPresenter: MovieDetailPresenterInterface {
    func getMovieDetail(with movieId: Int) {
        interactor.fetchMovieDetail(with: movieId)
    }
    
    func interactorDidFetchMovie(with result: Result<Movie, Error>) {
        switch result {
        case .success(let movie):
            view.update(with: movie)
        case .failure:
            view.update(with: "Periksa kembali internet anda")
        }
    }
    
}
