//
//  MovieDetailViewController.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 13/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieDetailViewController: UIViewController {
    
    var movieId = 0

    @IBOutlet weak var sv: UIScrollView!
    @IBOutlet weak var iv_backdrop: UIImageView!
    @IBOutlet weak var v_poster: UIView!
    @IBOutlet weak var iv_poster: UIImageView!
    @IBOutlet weak var lb_title: UILabel!
    @IBOutlet weak var lb_tagline: UILabel!
    @IBOutlet weak var lb_genre: UILabel!
    @IBOutlet weak var lb_overview: UILabel!
    @IBOutlet weak var lb_status: UILabel!
    @IBOutlet weak var cv_trailer: UICollectionView!
    // MARK: - Public properties -

    var presenter: MovieDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        sv.contentInsetAdjustmentBehavior = .never
        
        v_poster.layer.cornerRadius = 6
        v_poster.layer.masksToBounds = true
        
        presenter.getMovieDetail(with: movieId)
    }

}

// MARK: - Extensions -

extension MovieDetailViewController: MovieDetailViewInterface {
    func update(with movie: Movie) {
        DispatchQueue.main.async {
            self.iv_backdrop.setImage(from: movie.backdropPath ?? "")
            self.iv_poster.setImage(from: movie.posterPath ?? "")
            self.lb_title.text = (movie.title ?? "") + " (\(movie.releaseDate?.prefix(4) ?? ""))"
            self.lb_tagline.text = movie.tagline
            self.lb_genre.text = movie.genres?.map{ $0.name }.joined(separator: ", ")
            self.lb_overview.text = movie.overview
            self.lb_status.text = movie.status
        }
    }
    
    func update(with error: String) {
        DispatchQueue.main.async {
            let alert = UIAlertController(title: "Error", message: error, preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "OK", style: .default))
            self.present(alert, animated: true,completion: nil)
        }
    }
    
}
