//
//  MovieDetailInterfaces.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 13/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieDetailWireframeInterface: WireframeInterface {
}

protocol MovieDetailViewInterface: ViewInterface {
    func update(with movie: Movie)
    
    func update(with error: String)
}

protocol MovieDetailPresenterInterface: PresenterInterface {
    func getMovieDetail(with movieId: Int)
    
    func interactorDidFetchMovie(with result: Result<Movie, Error>)
    
//    func interactorDidFetchTrailer(with result: Result<Movie, Error>)
}

protocol MovieDetailInteractorInterface: InteractorInterface {
    func fetchMovieDetail(with movieId: Int)
    
    func fetchMovieTrailer(with movieId: Int)
}
