//
//  DashboardPresenter.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 12/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DashboardPresenter {
    
    // MARK: - Private properties -

    private unowned let view: DashboardViewInterface
    private let interactor: DashboardInteractorInterface
    private let wireframe: DashboardWireframeInterface

    // MARK: - Lifecycle -

    init(view: DashboardViewInterface, interactor: DashboardInteractorInterface, wireframe: DashboardWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension DashboardPresenter: DashboardPresenterInterface {
    func routeToGenre() {
        wireframe.routeToGenre()
    }
    
}
