//
//  DashboardWireframe.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 12/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DashboardWireframe: BaseWireframe<DashboardViewController> {

    // MARK: - Module setup -

    init() {
        let moduleViewController = DashboardViewController()
        super.init(viewController: moduleViewController)

        let interactor = DashboardInteractor()
        let presenter = DashboardPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DashboardWireframe: DashboardWireframeInterface {
    func routeToGenre() {
//        let vc = Genre2Router.createModule()
        self.navigationController?.pushWireframe(GenreWireframe())
//        self.viewController.navigationController?.pushViewController(vc, animated: true)
    }
    
}
