//
//  DashboardWireframe.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 12/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DashboardWireframe: BaseWireframe<DashboardViewController> {

    // MARK: - Module setup -

    init() {
        let moduleViewController = DashboardViewController()
        super.init(viewController: moduleViewController)

        let interactor = DashboardInteractor()
        let presenter = DashboardPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }

}

// MARK: - Extensions -

extension DashboardWireframe: DashboardWireframeInterface {
    func routeToGenre() {
        self.navigationController?.pushWireframe(GenreWireframe())
    }
    
    func routeToMovieList(with genreId: Int) {
        navigationController?.pushWireframe(MovieListWireframe(genreId: genreId))
    }
    
    func routeToMovieDetail(with movieId: Int) {
        navigationController?.pushWireframe(MovieDetailWireframe(movieId: movieId))
    }
    
}
