//
//  DashboardViewController.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 12/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DashboardViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: DashboardPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    
    @IBAction func actionTapped(_ sender: Any) {
    }
    @IBAction func comedyTapped(_ sender: Any) {
    }
    @IBAction func dramaTapped(_ sender: Any) {
    }
    @IBAction func moreTapped(_ sender: Any) {
        presenter.routeToGenre()
//        self.navigationController?.pushViewController(GenreViewController(), animated: true)
    }
}

// MARK: - Extensions -

extension DashboardViewController: DashboardViewInterface {
}
