//
//  DashboardInterfaces.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 12/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DashboardWireframeInterface: WireframeInterface {
    func routeToGenre()
}

protocol DashboardViewInterface: ViewInterface {
}

protocol DashboardPresenterInterface: PresenterInterface {
    func routeToGenre()
}

protocol DashboardInteractorInterface: InteractorInterface {
}
