//
//  DashboardInterfaces.swift
//  Makdempu Movie
//
//  Created by Ilyas Bintang Prayogi on 12/02/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DashboardWireframeInterface: WireframeInterface {
    func routeToGenre()
    
    func routeToMovieList(with genre: Genre)
    
    func routeToMovieDetail(with movieId: Int)
}

protocol DashboardViewInterface: ViewInterface {
    func update(with movies: [Movie])
    
    func update(with error: String)
}

protocol DashboardPresenterInterface: PresenterInterface {
    func getMovieList()
    
    func interactorDidFetchMovies(with result: Result<[Movie], Error>)
    
    func getAdditionalMovies(completion: @escaping ([Movie]) -> Void)
    
    func goToGenre()
    
    func goToMovieList(with genre: Genre)
    
    func goToMovieDetail(with movieId: Int)
}

protocol DashboardInteractorInterface: InteractorInterface {
    func fetchMovieList()
    
    func fetchAdditionalMovies(completion: @escaping (Result<[Movie], Error>) -> Void)
}
